# Installs software-config agent on boot for ubuntu with pip install

parameters:
  image: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)

resource_registry:
  "Heat::InstallConfigAgent": https://raw.githubusercontent.com/heat-ci/heat-templates/master/dev/bootconfig.yaml
