heat_template_version: 2013-05-23

parameters:
    image:
        type: string
        default: 77e32de8-3304-44f3-b230-436d95fceb19 # Debian 7 (Wheezy) (PVHVM)
    flavor:
        type: string
        default: performance1-1
    kitchen:
        description: URL for the kitchen to use
        type: string
    chef_version:
        description: Version of chef client to use
        type: string
        default: 11.12.2
    server_name:
        type: string
        default: gerrit_integration
        description: name of compute instance that heat will run on
    engine_region:
        type: string
        default: IAD
        description: region to run engine against
    api_region:
        type: string
        default: IAD
        description: region to run api against
    heat_version:
        type: string
        description: version of heat to fetch

resources:
    rabbitmq_password:
        type: "OS::Heat::RandomString"
        properties:
          length: 32
          sequence: hexdigits

    mysql_password:
        type: "OS::Heat::RandomString"
        properties:
          length: 32
          sequence: hexdigits
 
    heat_enc_key:
        type: "OS::Heat::RandomString"
        properties:
          length: 32
          sequence: hexdigits

    key_name:
        type: "OS::Heat::RandomString"
        properties:
          length: 32
          sequence: hexdigits

    ssh_key:
        type: "OS::Nova::KeyPair"
        properties:
            name: { get_attr: [key_name, value] }
            save_private_key: true

    heat_instance:
        type: "Rackspace::Cloud::Server"
        properties:
            name: { get_param: server_name }
            flavor: { get_param: flavor }
            image: { get_param: image }
            key_name: { get_resource: ssh_key }

    bootstrap_server:
        type: "Rackspace::Cloud::ChefSolo"
        properties:
            username: root
            private_key: { get_attr: [ssh_key, private_key] }
            host: { get_attr: [heat_instance, accessIPv4] }
            kitchen: { get_param: kitchen }
            chef_version: { get_param: chef_version }
            node:
                run_list:
                    - 'heat_test'

                mysql:
                   server_root_password: { get_attr: [mysql_password, value] }
                   server_debian_password: { get_attr: [mysql_password, value] }
                   server_repl_password: { get_attr: [mysql_password, value] }
               
                heat:
                    version: { get_param: heat_version }
                    mysql:
                       user: 'heat'
                       password: { get_attr: [mysql_password, value] }
                       database: 'heat'
                    rabbitmq:
                        username: 'heat'
                        password: { get_attr: [rabbitmq_password, value] }
                    engine:
                        region_name: { get_param: engine_region }
                    api:
                        region_name: { get_param: api_region }
                        nginx:
                            enable: true
                            vhost: "api.integration.rs-heat.com"
                            proxy_port: 8004
                            ssl:
                                certificate_file: '/server.crt'
                                certificate_key_file: '/server.key'
                                databag: 'db'
                                databag_item: 'db_item'
                passwords:
                    rabbitmq: 
                        _default:
                            heat: { get_attr: [rabbitmq_password, value] }
                    mysql:
                        _default:
                            heat: { get_attr: [mysql_password, value] }
                secrets:
                    heat_enc_key:
                        _default: { get_attr: [heat_enc_key, value] }
                db:
                    db_item:
                        certificate: { get_file: "https://9bc387c8156fcf75750f-b1d6f7307a55b0f1afd4eed45598d245.ssl.cf5.rackcdn.com/server.crt" }
                        private_key: { get_file: "https://9bc387c8156fcf75750f-b1d6f7307a55b0f1afd4eed45598d245.ssl.cf5.rackcdn.com/server.key" }

outputs:
    HEAT_IPv4:
        value: { get_attr: [heat_instance, accessIPv4] }
    HEAT_IPv6:
        value: { get_attr: [heat_instance, accessIPv6] }

