heat_template_version: 2014-10-16
parameters:
  flavor:
    type: string
  image:
    type: string
resources:
  server:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
